### PR TITLE
Allow for formatting of links in notes

### LINKED ISSUE #258: Request: parse links in notes area
Currently, the notes area just reproduces the text stored in the database for that workout verbatim.

It would be nice if the client could detect web links and format them as such. For example, rather than:

image
```html
<div class="card-content">Uploaded with Strava-to-FitTrackee
Original activity type on Strava was "Hike"
Original Strava link: https://strava.com/activities/123456789</div>
```

It could be shown as:

image
```html
<div class="card-content">Uploaded with Strava-to-FitTrackee
Original activity type on Strava was "Hike"
Original Strava link: <a href="https://strava.com/activities/123456789">https://strava.com/activities/123456789</a>
</div>
```

### PR DESCRIPTION
**Pull request by jat255**
Resolves #258.

This is a feature addition that adds link-detection and HTML sanitization and parsing to a workout's notes field. This is primarily making use of two new packages: [`linkify-html`](https://linkify.js.org/docs/linkify-html.html) and [`vue-3-sanitize`](https://github.com/vannsl/vue-3-sanitize). 

Here's how it looks in practice:

image

image

```html
<div class="card-content">
  <span data-v-98308232="">
    test with a plain website: <a href="https://google.com" target="_blank">https://google.com</a> 

    plain website inside HTML tag: &lt;div&gt;<a href="https://example.com" target="_blank">https://example.com</a>&lt;/div&gt; 

    script HTML tag: &lt;script&gt;alert('super hacker!')&lt;/script&gt;

    Another plain link: <a href="https://example.com/1234" target="_blank">https://example.com/1234</a>

    Already HTML link: <a href="https://example.com">HTML test</a>
  </span>
</div>
```

To accomplish this, I've edited the `WorkoutNotes` component to do a few new things:

1) If `notes` is defined, pass it through `linkifyHtml`, which detects any links in the text and wraps them in the appropriate `<a>` tags
2) After "linkifying", the notes string is sanitized using `vue-3-sanitize` (which uses [`sanitize-html`](https://github.com/apostrophecms/sanitize-html) to do the actual sanitization), and *only* the `<a>` tag is allowed; all other HTML tags will be escaped
3) With the HTML sanitized, the content is rendered in a `<span>` using the `v-html` directive

As can be seen in the example above, any HTML written in the note will not be evaluated/rendered, other than `<a>` tags which will. If a link is given as just text (probably the normal case), then `linkify-js` will handle converting that to a clickable link.

I realize this is potentially a security issue since the notes field is user-filled, but I believe with this sort of proper sanitization, it is okay, but I'm happy for suggestions, or if this is rejected due to security concerns, I understand.

### CODE REVIEW

**Comment by SamR1** [comment]
Hi,

Thanks for the PR. 
I'll take a look, but just a quick feedback: sanitization should also be done on the API side.

**Comment by jat255** [comment]
> sanitization should also be done on the API side

In my opinion, I think the API should only return what is exactly in the database, which is the raw content of the `notes` column for the given workout. The changes I implemented are basically just for display of the information in the front end app. I'm happy to take a look at putting that behavior into the API too if you think differently, but I would recommend against changing that part on the backend. (Expanding on that, my thought is that any consumer of the API may want to format things in their own way, and the backend shouldn't make any of those decisions for them; it should just return the data as-is from the DB)

**Comment by SamR1** [comment]
Hi,

I agree, the API should return data from the database (I was thinking sanitization before storing in database, but it will change user's input).
No problem to keep it like that for now.

For information, I may add comments in a next version (v0.8.x), and I was thinking allowing (very limited) markdown syntax in some inputs (it may have an impact on "Notes" too).

**Comment by SamR1** [comment]
Hi,

I tried the same text as in the example but the HTML links are not displayed correctly:

```
test with a plain website: https://google.com 

plain website inside HTML tag: <div>https://example.com</div>

script HTML tag: <script>alert('super hacker!')</script>

Another plain link: https://example.com/1234

Already HTML link: <a href="https://example.com">HTML test</a>
```

Screenshot 2022-11-09 at 11-51-29 FitTrackee

Screenshot 2022-11-09 at 11-51-42 FitTrackee

The URL in `a` tag seems to be linkified:
```html
<span data-v-98308232="">test with a plain website: <a href="[https://google.com](view-source:https://google.com/)" target="_blank">https://google.com</a> 

plain website inside HTML tag: &lt;div&gt;<a href="https://example.com</div>" target="_blank">https://example.com&lt;/div&gt;</a>

script HTML tag: &lt;script&gt;alert('super hacker!')&lt;/script&gt;

Another plain link: <a href="[https://example.com/1234](view-source:https://example.com/1234)" target="_blank">https://example.com/1234</a>

Already HTML link: &lt;a href="<a href="https://example.com&quot;>HTML" target="_blank">https://example.com"&gt;HTML</a> test&lt;/a&gt;</span>
```

In the PR description, you mentioned `linkify-html` but `linkify-string` is present in `package.json`.

**Comment by jat255** [comment]
@SamR1 my bad... I forgot to push up the commit that changed that functionality. I think it should be correct now.

**Comment by SamR1** [comment]
Thanks for the update.

During testing, a pre-existing bug prevents workout creation with gpx when double quotes are present in the notes. I'll fix it.

**Comment by jat255** [comment]
I gave it a test, and it seems to work for me. LGTM

**Comment by SamR1** [comment]
Thanks for your feedback.

**Pull request merged**
