### PR TITLE
New sport: Paragliding

### PR DESCRIPTION
**Pull request by dkm**
see issue https://github.com/SamR1/FitTrackee/issues/391

### CODE REVIEW

**Comment by dkm** [comment]
Appart from the icon, is it the correct changes needed to add a new workout?
The doc explicitly asks not to commit any generated js as these will be added before merging, so I've left them out.

**Comment by dkm** [comment]
The icon is great yes! I couldn't find anything matching the current style AND not confusing a paraglider with a parachute :D

For the stop speed threshold, it depends how it's handled. It's completely possible for the ground speed to be 0 for various reasons. It's probably not possible to have it 0 for more than few seconds though, so if the integration interval is long enough, 1km is probably ok. If it's shorter than say 30 or 15s, maybe it's easier to set the threshold to 0.1.

**Comment by SamR1** [comment]
OK, thanks for your feedback. I'll push my changes on your branch.

**Comment by SamR1** [comment]
I can't push on your branch (` ! [remote rejected]   dkm/add_paragliding -> dkm/add_paragliding (permission denied)`). Github does not display that I can push commits either.

Are there any restrictions on your repository?

**Comment by dkm** [comment]
Sorry, the checkbox was not selected, must have unchecked it when creating the PR. Should be good now!

**Comment by SamR1** [comment]
Thanks!

**Comment by dkm** [comment]
Not sure what's next, but if you're planning on merging this shortly, don't hesitate to amend the log for my commit that has "WIP" as sole description :). Or I'll do that later tonight.

**Comment by SamR1** [comment]
I'm planning to merge as soon as the tests are OK. I'll update the PR description ;)

**Pull request merged**
