### PR TITLE
New equipment for workouts

### LINKED ISSUE #259: Feature request: "Equipment" that can be associated with workouts
Some proprietary tools have a concept of "gear" or "equipment" that gets saved alongside a workout:

image

The nice feature with this is it allows you to keep track of how many miles, minutes, etc. you have put on a piece of equipment (useful for runners that swap out shoes every X miles or something). A similar feature in FitTrackee could be nice to have.

Implementation wise, it could probably look a lot like how "sports" are currently implemented, with a new DB table for pieces of equipment (each associated with a user), and then at upload time allowing for selecting of one (or more) pieces of associated equipment.

### PR DESCRIPTION
**Pull request by jat255**
This is still a WIP, but wanted to hopefully get some feedback. I'm pretty sure I'm done with the DB and API side of things on this addition, but still have to do the front-end stuff.

Resolves #259

## Running todo:

- Equipment support:
    - Database models:
        - [x] Add models for Equipment, Equipment type, workout/equipment M2M
    - API:
        - [x] Getting all equipment (for user or all as admin)
        - [x] Get equipment by type id
        - [x] Getting single equipment (for user or admin)
        - [x] Creating equipment
        - [x] Updating equipment
        - [x] Deleting equipment
        - [x] Associating workout with equipment
        - [x] Setting default equipment for sport type (user preferences)
        - [x] Filter workouts by equipment id
        - [x] Add equipments list in user data export
        - [x] API Documentation
    - API tests:
        - [x] GET /equipment_types
        - [x] GET /equipment_types/id
        - [x] GET /equipment
        - [x] GET /equipment/id
        - [x] POST /equipment
        - [x] PATCH /equipment/id
        - [x] DELETE /equipment/id
            - [x] test cascading of deletions to workout
            - [x] test cascading of deletions to default workout
        - [x] POST /auth/profile/edit/sports
        - [x] DELETE of user should delete any equipment they have
        - [x] export with equipments list
        - [x] GET /workouts
        - [x] POST /workout
        - [x] POST /workout/no_gpx
        - [x] PATCH /workout/id
        - [x] DELETE /workout/id
    - Front end:
        - [x] Displaying table of equipment
            - Creation date
            - Number of workouts
            - Number of miles
            - Total time (total and moving)
        - [x] Editing equipements
            - label
            - description
            - active status  
        - [x] Setting default for sport from user preferences
        - [x] Choosing equipment during workout creation/edit
            - Should default to any existing default when a sport is chosen
            - Inactive equipements are not displayed on workout creation
        - [x] Displaying equipment in workout details
        - [x] Adding equipment to filters on workout list
           - add possibility to filter workouts without equipements
        - [x] Administration
           - add possibility to disable equipments type (to match disabled sports)
           - prevent equipment creation with a deactivated type

### CODE REVIEW

**Comment by SamR1** [comment]
Hi,
Thanks for starting the implementation.

I will take a look at it soon.
No need to start the front-end for now, due to the upcoming changes with social features.

**Comment by jat255** [comment]
> I will take a look at it soon. No need to start the front-end for now, due to the upcoming changes with social features.

That's great, since I quickly realized I was in over my head (I have no idea how to do front-end dev), and wasn't making much progress :sweat_smile:

**Comment by SamR1** [comment]
Hi @jat255 

I'm really sorry for the late feedback.  
I had originally planned to take a look, after the social features (but there's still some work to do).

I've made a few changes and there's still the part on default equipments to implement on the client side.

Some screenshots (may change):

- Administration

Screenshot 2024-03-06 at 20-35-53 FitTrackee - Equipments administration

I removed treadmill because there's no sport for it.

- User Equipements

Screenshot 2024-03-06 at 20-43-58 FitTrackee - Équipements

Screenshot 2024-03-06 at 20-31-56 FitTrackee - Equipments

It remains to display distance correctly.

- Equipments on Workout detail

Screenshot 2024-03-06 at 20-32-35 FitTrackee - Workout

- Filter on Equipement on Workout List

Screenshot 2024-03-06 at 20-32-10 FitTrackee - Workouts

- Workout creation

Screenshot 2024-03-06 at 20-33-08 FitTrackee - Add a workout

Thanks again for starting the implementation.

**Comment by SamR1** [comment]
Additional changes on API side:
  - store equipement totals in `equipments` table (to avoid fetching all related workouts to calculate totals)
  - unique contraint on `label` and `user_id` only for `equipments` table to avoid error when selecting an equipment with same label
  - **POST** `/workout` & **POST**  `/workout/no_gpx`: if `equipment_ids` is not provided and default equipment exists for the sport, they will be associated to make it easier to add equipments using only the API (for instance with an import script)
 
---

Screenshots

- updated equipment detail

Screenshot 2024-03-17 at 12-29-04 FitTrackee - Equipments

- sport detail (new page)

Screenshot 2024-03-17 at 12-29-09 FitTrackee - Sports

**Comment by SamR1** [comment]
Last changes:
- handle equipment types deactivation (to match sports deactivated by admin)
- it is not possible to create an equipment with a deactivated type
- only valid equipement for a given sport can be added

**Pull request merged**
