### PR TITLE
Add colors-dark.scss

### PR DESCRIPTION
**Pull request by DavidHenryThoreau**
https://github.com/SamR1/FitTrackee/issues/419
https://github.com/SamR1/FitTrackee/issues/113

### CODE REVIEW

**Comment by SamR1** [comment]
Hi,

Thanks for the updated PR.

Some feedback:
- As the file `colors-dark.scss` is not imported, the dark mode cannot be displayed.
- To update inputs style, `color-scheme` must be set.
- I also notice the file `colors.scss` is incomplete, some colors are defined directly in Vue components, my bad...
- Workout map and chart are not taken into account.

So I've made a few changes and corrections:
- add the missing color variables
- tweak some colors (the dark theme is closer to the documentation one)
- apply the dark theme to workout map and chart (requires some changes)
- add a user preference. By default, the theme depends on browser preferences. This user preference overrides the browser preference.


Some screenshots (on Firefox) :

- desktop

| Dashboard | Workout detail | Default sport colors (unchanged) |
|-----------|----------------|----------------------------------|
| Screenshot 2023-12-17 at 11-43-21 FitTrackee - Dashboard | Screenshot 2023-12-17 at 11-43-46 FitTrackee - Workout  | Screenshot 2023-12-17 at 11-43-56 FitTrackee - Sports administration |


- mobile

| Dashboard | Workout detail | Workout list |
|-----------|----------------|----------------------------------|
|Screenshot_20231217-113418_Fennec  | Screenshot_20231217-113506_Fennec | Screenshot_20231217-113533_Fennec | 

Maybe some colors need adjustment.

**Comment by DavidHenryThoreau** [comment]
Yes I've just set new dark colors to the css file I've not set html intergation.
Screenshots show adjustment, really nice !

**Comment by SamR1** [comment]
Hi,

thanks for the feedback.

compared to previous images, I've improved the contrast of charts axes:

| dashboard | workout detail |
| ---------------- | --------------------- |
| Screenshot 2023-12-20 at 10-07-01 FitTrackee - Dashboard | Screenshot 2023-12-20 at 10-06-52 FitTrackee - Workout  |

**Comment by DavidHenryThoreau** [comment]
Right, It's really better UX/UI
My eyes say thank you :+1:

**Pull request merged**
