### PR TITLE
German translation (#190)

### PR DESCRIPTION
**Pull request by gorgobacka**
Add translation files for frontend and backend.

Solves: https://github.com/SamR1/FitTrackee/issues/190

### CODE REVIEW

**Comment by gorgobacka** [comment]
I hope everything is correct.

I tested the frontend and it's working. But I'm not sure how to check, if the content of the emails is also replaced with the correct files.

**Comment by SamR1** [comment]
Thanks for the translation :)

It looks ok, just some minor style issues on records cards or workouts table.

For instance:

Screenshot 2022-06-29 at 15-19-59 FitTrackee 

Screenshot 2022-06-29 at 15-19-45 FitTrackee

I'll look how to fix that.

**Comment by escuco** [comment]
> It looks ok, just some minor style issues on records cards or workouts table.
> I'll look how to fix that.

Eventually (and only usable for this case) changing `Durchschn. `and `Ave.` by the `Ø`-Symbol, which is international.

**Comment by SamR1** [comment]
> > It looks ok, just some minor style issues on records cards or workouts table.
> > I'll look how to fix that.
> 
> Eventually (and only usable for this case) changing `Durchschn. `and `Ave.` by the `Ø`-Symbol, which is international.

Thanks for the suggestion :)

I managed to fix text alignment with CSS:
Screenshot 2022-06-29 at 17-19-20 FitTrackee

I can center the text, if you prefer:
Screenshot 2022-06-29 at 17-23-26 FitTrackee

But it's more tricky for the workouts table.

**Comment by gorgobacka** [comment]
Thanks for fixing the styling. The centered text looks better.
Unfortunately, the German words are much longer then the English equivalent.
I also tried the Ø -Symbol before. But I thought it doesn't looked good enough while being the only symbol in the table headers.

**Comment by SamR1** [comment]
I manage to improve the workouts list display a bit:

- before

Screenshot 2022-07-02 at 10-02-44 FitTrackee

- after

Screenshot 2022-07-02 at 10-04-41 FitTrackee

**Pull request merged**
