### PR TITLE
Add docker-release.sh in order to build and push to Docker hub

### PR DESCRIPTION
**Pull request by DavidHenryThoreau**
#126

### CODE REVIEW

**Comment by SamR1** [comment]
Hi,

Thanks for the updated PR.

As the docker files present in this repository are just for evaluation (not suitable for production), it will build an image for evaluation only.

**Comment by DavidHenryThoreau** [comment]
Right, but for production how do you plan to build the docker image ?

**Comment by SamR1** [comment]
Hard to say, I have no experience deploying with Docker in production :/

**Comment by DavidHenryThoreau** [comment]
I've read about https://docs.docker.com/docker-hub/builds/link-source/

**Comment by DavidHenryThoreau** [comment]
It's possible to let GitHub build docker image automatically every time you merge on `master` branch.

You can create a GitHub action by using this link (I've made some test in my fork) : 
https://github.com/SamR1/FitTrackee/new/master?filename=.github%2Fworkflows%2Fdocker-publish.yml&workflow_template=ci%2Fdocker-publish

**Comment by DavidHenryThoreau** [comment]
Another example for GitHub workflows : 
https://github.com/joaovitoriasilva/endurain/tree/master/.github/workflows

**Comment by DavidHenryThoreau** [comment]
Docker images are based on ubuntu, but size is bigger than GiB, there's a way to reduce, other docker's project are smaller

**Comment by jovandeginste** [comment]
I built them for my personal usage, with these changes, reducing the image sizes to:

- fittrackee: 560MB
- fittrackee_client: 357MB

```diff
diff --git a/.dockerignore b/.dockerignore
index db3149ba..24c43d49 100644
--- a/.dockerignore
+++ b/.dockerignore
@@ -10,3 +10,5 @@ docker-compose-dev.yml
 Makefile.custom.config
 *.log
 data
+fittrackee_client
+db
diff --git a/Dockerfile b/Dockerfile
index ac910520..9da0f2f5 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,4 @@
-FROM python:3.10
+FROM python:3.10-slim

 # set working directory
 RUN mkdir -p /usr/src/app
@@ -11,8 +11,8 @@ COPY . /usr/src/app
 ENV VIRTUAL_ENV=/opt/venv
 RUN python3 -m venv $VIRTUAL_ENV
 ENV PATH="$VIRTUAL_ENV/bin:$PATH"
-RUN pip install --upgrade pip
-RUN pip install poetry
+RUN pip install --no-cache-dir --upgrade pip
+RUN pip install --no-cache-dir poetry
 RUN . $VIRTUAL_ENV/bin/activate && poetry install --no-interaction --quiet

 # run fittrackee server
diff --git a/fittrackee_client/Dockerfile b/fittrackee_client/Dockerfile
index e1c9e5f3..9c929f89 100644
--- a/fittrackee_client/Dockerfile
+++ b/fittrackee_client/Dockerfile
@@ -1,9 +1,8 @@
-FROM node:18
+FROM node:18-alpine

 MAINTAINER SamR1@users.noreply.github.com

 # set working directory
-RUN mkdir /usr/src/app
 WORKDIR /usr/src/app

 # add `/usr/src/app/node_modules/.bin` to $PATH
@@ -18,7 +17,8 @@ ENV VITE_APP_API_URL $VITE_APP_API_URL
 # install dependencies
 COPY package.json /usr/src/app/package.json
 COPY yarn.lock /usr/src/app/yarn.lock
-RUN yarn install --silent
+RUN yarn install --silent && yarn cache clean --force
+RUN npm run build

 # copy source
 COPY . /usr/src/app/
```

**Pull request closed without merging**
