### PR TITLE
Implementing alternative weather API (VisualCrossing.com)

### PR DESCRIPTION
**Pull request by jat255**
As described in #51, DarkSky's API will be retired in a few months and isn't open for new signups, meaning new users of FitTrackee cannot get weather data.

After analyzing a few options, I've chosen to implement VisualCrossing.com's timeline API.

Tasks:
- [x] Add environment variable and backend python code to get weather data from new API
- [x]  Add icons for VC's particular status codes
- [x] Update client to show wind speed in miles per hour in "imperial" unit mode (at least in the US, mph is used for wind rather than ft/s)
- [x] Update client to show temperature in Fahrenheit in "imperial" unit mode
- [x] Tests

### CODE REVIEW

**Comment by jat255** [comment]
@SamR1 aside from tests (are there existing tests for weather functionality? I don't see them, if so), this should be ready for review.

It implements VisualCrossing as a new weather data source, and makes some small tweaks to how the weather is displayed when using Imperial units. It looks as follows:

Imperial:
image

Metric:
image

I'm unclear why the sun is displaying as blue... The icon I uploaded has it as yellow.

**Comment by SamR1** [comment]
Hi

Thanks for the PR. 

Just for information, I haven't yet reviewed the alternative weather service providers (sorry, I don't have a lot of free time at the moment to work on FitTrackee).

**Comment by jat255** [comment]
:+1:  I went ahead with VisualCrossing.com due to limitations I felt would cause issues with the other providers mentioned in that issue. Namely, Openmeteo's history API is delayed 5-7 days, so is not useful in real-time, and meteostat has a relatively low free tier of 500 calls/month. VisualCrossing seemed like it checked all the boxes, so to speak.

I implemented it with a new environment variable `VC_WEATHER_API_KEY` and a set of icons that match what their API might return. It could be more general by instead using something like two env variables such as, and then selecting the right code to use in `weather.py`, but I wasn't sure if supporting multiple APIs was really worth it (since DarkSky is going away in a month or two):

```sh
WEATHER_API=visualcrossing   # or darksky, meteostat, openmeteo, etc.
WEATHER_API_KEY=123456abcdef
```

**Comment by SamR1** [comment]
Hi,

So far, I haven't found the perfect replacement for **DarkSky**.   
I reviewed some weather APIs, I updated the [issue](https://github.com/SamR1/FitTrackee/issues/51). It's not exhaustive, I may review others later.
**VisualCrossing** historical data is only per hour (**DarkSky** is more accurate).
Another alternative is **OpenWeather One Call API 3.0** but credit card is required if I'm not wrong.

I worked on a base for multiple APIs support to keep **DarkSky** in addition to **VisualCrossing** and in case other APIs are supported in the future: https://github.com/SamR1/FitTrackee/compare/64d770a016a49cae61fb614d4369f97b2f8975be...alternate_weather_api
I refactored some code, in particular to add tests on API and Client sides. 
I prefer to keep the generic icons (since **VisualCrossing** icon labels match existing ones with default value ([iconSet=icons1](https://www.visualcrossing.com/resources/documentation/weather-api/defining-icon-set-in-the-weather-api/))).

If it's OK for you, I will push the changes on this PR.

**Comment by jat255** [comment]
Thanks for pushing this through! I just got around to updating after a while, and it appears to be working well for me. Different but related question... do you know if there's a simple-ish way to reprocess old workouts to add weather info? I see it's stored with each workout in the DB as a JSON in the `weather_start` and `weather_end`. I could certainly write a script to do this, but I figured I should check if there's a tool for this already

**Comment by SamR1** [comment]
Hi,

Unfortunately it's not possible to reprocess workouts for now (maybe in the version with workout processing rewrite).

**Comment by jat255** [comment]
Gotcha, I see that in [`edit_workout`](https://github.com/SamR1/FitTrackee/blob/03dddc41f93afbc93da653cf157dd0e74026ad65/fittrackee/workouts/utils/workouts.py#L206), weather information is not processed at all, so even via a PATCH command the weather info cannot be edited.

To get around this I wrote a little script that uses the FT API to get workouts and their GPX files, then uses the FT code to call the weather API, then finally directly updates the `weather_start` and `weather_end` columns in the backend database directly. Hacky, but it works!

That's available [here](https://gist.github.com/jat255/9bc27ac511bed5bd1c10e47db1b7e3ce) in case that helps anyone. It makes use of/requires the `FitTrackeeConnector` class from [`s2f.py`](https://github.com/jat255/strava-to-fittrackee/blob/main/s2f.py) in https://github.com/jat255/strava-to-fittrackee

**Pull request merged**
