### PR TITLE
Add ability to customize format used to display dates throughout the app

### LINKED ISSUE #112: allow user to change date format

### PR DESCRIPTION
**Pull request by jat255**
Resolves #112 

This PR adds a user setting to the database, together with associated UI bits to allow for control over how dates are displayed within the app. (fair warning, I've never worked with Vue before, so I may have done some terrible/ugly things).

I implemented the user setting as a "select":

image

```
            <option value="dd/MM/yyyy">dd/MM/yyyy - 08/07/2022</option>
            <option value="MM/dd/yyyy">MM/dd/yyyy - 07/08/2022</option>
            <option value="MMM. do, yyyy">MMM. do, yyyy - Jul. 8th, 2022</option>
            <option value="yyyy-MM-dd">yyyy-MM-dd - 2022-07-08</option>
```

I had originally done it as free text, but if an invalid format string was entered, it would cause errors, and I could not figure out an easy way to validate the format strings before storing them in the database. Instead, I put in a few format options that I think should be the most common. I'm happy to change the options, if desired.

The result is everywhere in the app a date is displayed, it will use the user preference. A few examples:

image

image

A few other notes:

 - As I mentioned, I've never done Vue before, so some things might not make any sense and I'm happy to accept changes
 - I didn't add tests specifically for the date format, but did edit some of the `records.spec.ts` tests to use various date formats. I would have to investigate how to do this more formally, if that's required.
 - The translations I added for German and French are just taken straight from Google Translate, so there may be better terminology to use in those languages
 - I added some additional `docker-` make targets, since I set up my development environment using docker and it looked like a few were missing 
 - I couldn't get the `e2e` tests to run properly (kept getting a connection error from Selenium), so I'm not sure if those are passing

### CODE REVIEW

**Comment by jat255** [comment]
The CI test failed, but running `docker-check-all` passed when I ran it on my system.

**Comment by SamR1** [comment]
Hi!

Thanks a lot for the PR! I'll take a look.  

For the errors on CI, it seems to be related to the latest version of PostgreSQL (v15 has just been released).

**Comment by SamR1** [comment]
Hi,

Thanks again.
FYI, I just merged PostgreSQL 15 fix and new sport addition on dev branch (so the migraton must be updated and renamed).

Some feedback:
- the new column `date_format` can be initialized to a default value in the migration (so it can be set as non-nullable)
- dates are not translated when selecting the format `MMM. do, yyyy` (**date-fns** provides [internationalization](https://date-fns.org/v2.29.3/docs/I18n)).
Note: with french and german, using this format adds an extra dot.
For instance, with the date  `2022-10-31T09:00:00`, it displays:
  - "Oct. 31st, 2022" with `enUS` locale 
  - "oct.. 31ème, 2022" with `fr` locale
  - "Okt.. 31., 2022" with `de` locale   
In french the format should be `do MMM yyyy`, for instance "31 oct. 2022" (I don't know for german).

I can work on that today, if you prefer.

**Comment by jat255** [comment]
> I can work on that today, if you prefer.

Hmm, I'm not overly familiar with `data-fns`, so you might be more effective in getting this working quickly compared to me. If it's not too much hassle, I'd be happy to let you get this one over the finish line! Perhaps we can leave out the `MMM` format, or just provide more options that work with the international formats as well? I primarily wanted the ISO `yyyy-MM-dd` style and American style of `MM/dd/yyyy` for my own use.

**Comment by SamR1** [comment]
No problem to work on it.

For the the `MMM` format, I'll try to handle different locales.

**Comment by SamR1** [comment]
I added the following format for each locale:
- `en`: `MMM. do, yyyy`
- `fr`: `d MMM yyyy`
- `de`: `do MMM yyyy`

| en | fr | de |
| --- | --- | --- |
|  en | fr | de |

And I changed the default format to `MM/dd/yyyy` (since the default language is `en`).

**Pull request merged**
