### PR TITLE
Automatically refresh upstream and create Docker image

### PR DESCRIPTION
**Pull request by DavidHenryThoreau**

### CODE REVIEW

**Comment by DavidHenryThoreau** [comment]
@SamR1 I'm working on docker images i'm looking at https://github.com/SamR1/FitTrackee/blob/master/db/create.sql , why do you drop database, if container restart it'll drop the DB.

I've also created a repository in order to build fittrackee-db https://github.com/DavidHenryThoreau/fittrackee-db add all steps in the Dockercompose.yaml https://github.com/SamR1/FitTrackee/pull/541/commits/f49fc1865142355035ac7552dc95ebd82d41c9a2

**Comment by DavidHenryThoreau** [comment]
TODO : Run `ftcli db upgrade` when fittrackee docker container starts in order to populate the databse

**Comment by DavidHenryThoreau** [comment]
Images are built form source, need some testers : 
`docker compose pull && docker compose up -d`

Have fun !

**Comment by DavidHenryThoreau** [comment]
TODO : 

- [ ] Optimize Dockerfile reduce size try : try https://github.com/docker-library/python/blob/1b7a1106674a21e699b155cbd53bf39387284cca/3.10/alpine3.19/Dockerfile

- [ ] Do not build PostgreSQL image (not necessary at the moment)

- [ ] Add Redis alternative

**Comment by SamR1** [comment]
Hi,

> I'm working on docker images i'm looking at https://github.com/SamR1/FitTrackee/blob/master/db/create.sql , why do you drop database, if container restart it'll drop the DB.

The SQL script allows to recreate databases easily for tests during developpement.

About its execution (in `docker-entrypoint-initdb.d`):

> Warning: scripts in /docker-entrypoint-initdb.d are only run if you start the container with a data directory that is empty; any pre-existing database will be left untouched on container startup.

source: https://hub.docker.com/_/postgres/

As I said in the other [MR](https://github.com/SamR1/FitTrackee/pull/463#issuecomment-1868234737), docker files present in this repository are intended for evaluation or development only. So the configuration is not suitable for production. Other changes or steps may be necessary to secure deployment in production.

**Comment by DavidHenryThoreau** [comment]
> Hi,
> 
> > I'm working on docker images i'm looking at https://github.com/SamR1/FitTrackee/blob/master/db/create.sql , why do you drop database, if container restart it'll drop the DB.
> 
> The SQL script allows to recreate databases easily for tests during developpement.
> 
> About its execution (in `docker-entrypoint-initdb.d`):
> 
> > Warning: scripts in /docker-entrypoint-initdb.d are only run if you start the container with a data directory that is empty; any pre-existing database will be left untouched on container startup.
> 
> source: https://hub.docker.com/_/postgres/

Thanks for explanations 
> 
> As I said in the other [MR](https://github.com/SamR1/FitTrackee/pull/463#issuecomment-1868234737), docker files present in this repository are intended for evaluation or development only. So the configuration is not suitable for production. Other changes or steps may be necessary to secure deployment in production.

At the moment yes, but some users are waiting to use fittrackee in docker in production, that's why I'm working at it.
If all steps are green maybe you can merge to master.

**Comment by DavidHenryThoreau** [comment]
I'm trying to import gpx file I'm getting this error  `Erreur lors du traitement du fichier gpx.`

```
2f332d7b38db:/usr/src/app# tail -f fittrackee.log
2024/05/17 15:47:17 - fittrackee - ERROR - could not download 4 tiles: [(525, 358, ''), (525, 359, ''), (526, 358, ''), (526, 359, '')]
2024/05/17 15:47:17 - werkzeug - INFO - 192.168.1.2 - - [17/May/2024 15:47:17] "POST /api/workouts HTTP/1.1" 500 -
```

**Pull request closed without merging**
