### PR TITLE
Added total elevation to dashboard

### PR DESCRIPTION
**Pull request by Fmstrat**
header

### CODE REVIEW

**Comment by SamR1** [comment]
Hi,

Some feedback before review:
- is it possible to make change from `dev` branch?
- I prefer to keep 4 cards for better display.  
  In this case, I think the last card (number of sports) can be removed (this information is displayed in user profile).

**Comment by Fmstrat** [comment]
@SamR1 I've migrated this to the `dev` branch, however I think there may be another error preventing me from testing. Using Docker and in the client:
```
$ make docker-serve-client
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
fittrackee-redis is up-to-date
fittrackee-db is up-to-date
fittrackee-mailhog is up-to-date
fittrackee is up-to-date
Recreating fittrackee_client ... done
yarn run v1.22.18
$ vue-cli-service serve
 ERROR  Error loading /usr/src/app/vue.config.js:
 ERROR  TypeError: defineConfig is not a function
TypeError: defineConfig is not a function
    at Object.<anonymous> (/usr/src/app/vue.config.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at exports.loadModule (/usr/src/app/node_modules/@vue/cli-shared-utils/lib/module.js:79:14)
    at Service.loadUserOptions (/usr/src/app/node_modules/@vue/cli-service/lib/Service.js:330:22)
    at Service.init (/usr/src/app/node_modules/@vue/cli-service/lib/Service.js:70:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: 1
make: *** [Makefile:62: docker-serve-client] Error 1
```
This is on a fresh `dev` branch.

**Comment by Fmstrat** [comment]
Here's the draft if you'd like to see it (untested of course): https://github.com/SamR1/FitTrackee/compare/dev...Fmstrat:elevation2?expand=1

**Comment by SamR1** [comment]
Hi,

Thanks for the rebase.
Quick feedback:
- since it's possible to add a workout without gpx, the ascent for a workout can be `null` in database (some tests are broken due to `null` values)
- the total ascent returned by the API must be a float. I have errors

**Comment by Fmstrat** [comment]
Looks like `pip` failed installing dependencies on that last test. I *think* this one is good.

**Pull request merged**
